version: '3.8'
services:

  #
  # Deploy Elasticsearch using manually configured security based on trusted PKI
  #
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    hostname: elasticsearch-internal.authsamples-dev.com
    ports:
      - 9200:9200
    volumes:
      - ./certs/authsamples-dev.ca.pem:/usr/share/elasticsearch/config/certs/authsamples-dev.ca.crt
      - ./certs/authsamples-dev.ssl.p12:/usr/share/elasticsearch/config/certs/authsamples-dev.ssl.p12
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'true'
      xpack.security.autoconfiguration.enabled: 'false'
      xpack.security.http.ssl.enabled: 'true'
      xpack.security.http.ssl.keystore.path: '/usr/share/elasticsearch/config/certs/authsamples-dev.ssl.p12'
      xpack.security.http.ssl.keystore.password: 'Password1'
      xpack.security.http.ssl.certificate_authorities: '/usr/share/elasticsearch/config/certs/authsamples-dev.ca.crt'
      ELASTIC_PASSWORD: '${ELASTIC_PASSWORD}'

  #
  # Deploy Kibana with a dummy user account different to 'elastic', to prevent startup failures
  #
  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.2
    hostname: kibana-internal.authsamples-dev.com
    ports:
      - 5601:5601
    volumes:
      - ./certs/authsamples-dev.ca.pem:/usr/share/kibana/config/certs/authsamples-dev.ca.crt
      - ./certs/authsamples-dev.ssl.p12:/usr/share/kibana/config/certs/authsamples-dev.ssl.p12
    environment:
      ELASTICSEARCH_HOSTS: 'https://elasticsearch-internal.authsamples-dev.com:9200'
      ELASTICSEARCH_USERNAME: '${KIBANA_USER}'
      ELASTICSEARCH_PASSWORD: '${KIBANA_PASSWORD}'
      SERVER_PUBLICBASEURL: 'https://logs.authsamples-dev.com:5601'
      SERVER_SSL_ENABLED: 'true'
      SERVER_SSL_KEYSTORE_PATH: '/usr/share/kibana/config/certs/authsamples-dev.ssl.p12'
      SERVER_SSL_KEYSTORE_PASSWORD: 'Password1'
      ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES: '/usr/share/kibana/config/certs/authsamples-dev.ca.crt'

  #
  # Deploy Filebeat to point to an API share on the host computer, and with settings in the filebeat.yml file
  #
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.3.2
    hostname: filebeat-internal.authsamples-dev.com
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./certs/authsamples-dev.ca.pem:/usr/share/filebeat/certs/authsamples-dev.ca.crt
      - ../../../oauth.apisample.nodejs/logs:/var/log/finalapi
      - ../../../oauth.tokenhandler.docker/logs:/var/log/oauthagent
    environment:
      ELASTICSEARCH_USERNAME: '${ELASTIC_USER}'
      ELASTICSEARCH_PASSWORD: '${ELASTIC_PASSWORD}'
