filebeat.inputs:
- type: log
  paths:
  - /var/log/api/*.log
  - /var/log/oauthagent/*.log
  json:
    keys_under_root: true
    add_error_key: false

output.elasticsearch:
  hosts: ['https://elasticsearch-internal.authsamples-dev.com:9200']
  username: elastic
  password: Password1
  index: "apilogs-%{+yyyy.MM.dd}"
  pipelines:
  - pipeline: apilogs
  ssl:
    certificate_authorities: ['/usr/share/filebeat/certs/authsamples-dev.ca.crt']

setup:
  ilm:
    enabled: false
  template:
    name: apilogs
    pattern: apilogs-*

processors:
- drop_fields:
    fields: ['agent', 'ecs', 'host', 'input', 'version']
