#
# Initialize Elastic with a schema and with an ingest pipeline for our API logs
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: es-initdata-job
---
apiVersion: batch/v1
kind: Job
metadata:
  name: es-initdata-job
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      labels:
        app: es-initdata-job
        spire-managed-identity: 'true'
      annotations:
        inject.istio.io/templates: 'sidecar,spire'
    spec:
      serviceAccountName: es-initdata-job
      restartPolicy: Never
      volumes:
        - name: schema-json
          configMap:
            name: schema-json
        - name: ingestion-json
          configMap:
            name: ingestion-json
        - name: initdata-script
          configMap:
            name: initdata-script
      containers:
        - name: es-initdata-job
          image: $DOCKER_IMAGE
          volumeMounts:
          - name: schema-json
            mountPath: /tmp/schema.json
            subPath: schema.json
            readOnly: true
          - name: ingestion-json
            mountPath: /tmp/ingestion-pipeline-cloudnative.json
            subPath: ingestion-pipeline-cloudnative.json
            readOnly: true
          - name: initdata-script
            mountPath: /tmp/initdata.sh
            subPath: initdata.sh
            readOnly: true
          env:
            - name: IS_ISTIO
              value: 'true'
            - name: ELASTIC_URL
              value: http://elasticsearch-svc:9200
            - name: ELASTIC_USER
              value: elastic
            - name: ELASTIC_PASSWORD
              value: Password1
            - name: KIBANA_SYSTEM_USER
              value: kibana_system
            - name: KIBANA_PASSWORD
              value: Password1
            - name: SCHEMA_FILE_PATH
              value: /tmp/schema.json
            - name: INGESTION_PIPELINE_FILE_PATH
              value: /tmp/ingestion-pipeline-cloudnative.json
          command:
            [
              "bash",
              "/tmp/initdata.sh"
            ]
