#
# Expose Kibana externally
#
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-ingress-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: mycluster-com-tls
    hosts:
    - logs.mycluster.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kibana-virtual-service
spec:
  hosts:
  - logs.mycluster.com
  gateways:
  - istio-ingress-gateway
  http:
  - route:
    - destination:
        host: kibana-svc
        port:
          number: 5601
